# Generated by Django 3.2.5 on 2021-07-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_bid', models.CharField(db_index=True, max_length=400)),
                ('type_bid', models.IntegerField(choices=[(1, 'fix'), (2, 'consultation'), (3, 'service')])),
                ('status', models.IntegerField(choices=[(1, 'open'), (2, 'in work'), (3, 'finished')])),
                ('date_create', models.DateField(auto_now_add=True)),
                ('client', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.SlugField(max_length=30)),
                ('client_telegram_user_id', models.CharField(max_length=10)),
                ('client_date_registration', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
