# Generated by Django 3.2.5 on 2021-07-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.SlugField(max_length=30)),
                ('client_telegram_user_id', models.CharField(max_length=10)),
                ('client_date_registration', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_bid', models.IntegerField(choices=[(1, 'fix'), (2, 'consultation'), (3, 'service')])),
                ('staff_id', models.IntegerField(blank=True, null=True)),
                ('text_bid', models.CharField(max_length=400)),
                ('title', models.CharField(db_index=True, default='Bid', max_length=100)),
                ('status', models.IntegerField(choices=[(1, 'open'), (2, 'in work'), (3, 'finished')], default=1)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('notifications', models.BooleanField(default=False)),
                ('creator', models.ManyToManyField(blank=True, related_name='bids', to='API.ClientModel')),
            ],
        ),
    ]
