# Generated by Django 3.2.5 on 2021-07-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='bidmodel',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='bidmodel',
            name='staff_id',
            field=models.ManyToManyField(blank=True, related_name='bids', to='API.StaffModel'),
        ),
    ]
