# Generated by Django 3.2.5 on 2021-07-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='client_date_registration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
